export enum BucketStatus {
  READ = 'READ',
  REJECTED = 'REJECTED',
  DECLINED = 'DECLINED',
  ACCEPTED = 'ACCEPTED',
  FINISHED = 'FINISHED',
}

export enum TechnicBody {
  STANDARD = 'STANDARD',
  ATV = 'ATV',
  LONG_VEHICLE = 'LONG_VEHICLE',
  TRAILER = 'TRAILER',
  LOW_LOADER = 'LOW_LOADER',
  BOOM = 'BOOM',
  STATIONARY = 'STATIONARY',
  LINEAR = 'LINEAR',
}

export enum OrderDetailServices {
  TRAILER = 'TRAILER',
  LOW_LOADER = 'LOW_LOADER',
  SLINGER_SERVICE = 'SLINGER_SERVICE',
  CRADLE = 'CRADLE',
  BUNKS = 'BUNKS',
  PYRAMID = 'PYRAMID',
  SUCTION_CUP = 'SUCTION_CUP',
  REAR_OVERHANG = 'REAR_OVERHANG',
}
